// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
int two_();
extern "C" SEXP _testrdocker_two_() {
  BEGIN_CPP11
    return cpp11::as_sexp(two_());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_testrdocker_two_", (DL_FUNC) &_testrdocker_two_, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_testrdocker(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
