# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.name }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04,   r: 'release'}
          
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check package on Debian 12 with Clang
        run: |
          docker pull pachadotdev/debian-clang:latest
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace pachadotdev/debian-clang:latest bash -c "Rscript -e 'devtools::check()'"

      - name: Check package on Debian 12 with GCC
        run: |
          docker pull pachadotdev/debian-gcc:latest
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace pachadotdev/debian-gcc:latest bash -c "Rscript -e 'devtools::check()'"

      - name: Check package on Fedora 40 with Clang
        run: |
          docker pull pachadotdev/fedora-clang:latest
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace pachadotdev/fedora-clang:latest bash -c "Rscript -e 'devtools::check()'"

      - name: Check package on Fedora 40 with GCC
        run: |
          docker pull pachadotdev/fedora-gcc:latest
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace pachadotdev/fedora-gcc:latest bash -c "Rscript -e 'devtools::check()'"
